spring:
  application:
    name: auth-service

  cloud:
    consul:
      discovery:
        service-name: auth-service
        health-check-path: /actuator/health
        health-check-interval: 10s
        metadata:
          gateway-path: /api/auth/**

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-ms: ${JWT_ACCESS_TOKEN_VALIDITY_MS}
  refresh-token-validity-ms: ${JWT_REFRESH_TOKEN_VALIDITY_MS}

frontend:
  oauth-callback-url: ${FRONTEND_OAUTH_CALLBACK_URL}
  oauth-signup-url: ${FRONTEND_OAUTH_SIGNUP_URL}

auth:
  cookie:
    access-token-name: ${AUTH_ACCESS_TOKEN_COOKIE_NAME}
    refresh-token-name: ${AUTH_REFRESH_TOKEN_COOKIE_NAME}
    path: ${AUTH_COOKIE_PATH}
    domain: ${AUTH_COOKIE_DOMAIN}
    http-only: ${AUTH_COOKIE_HTTP_ONLY}
    secure: ${AUTH_COOKIE_SECURE}
    same-site: ${AUTH_COOKIE_SAME_SITE}
