spring:
  config:
    import: optional:file:./secrets/application-develop-secret.yml
    activate:
      on-profile: develop

  cloud:
    consul:
      enabled: true
      host: localhost
      port: 18500

server:
  port: 18087

openapi:
  docs-export:
    enabled: true
