input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if ![environment] {
    mutate {
      add_field => { "environment" => "${ENV:unknown}" }
    }
  }

  if ![application] {
    mutate {
      add_field => { "application" => "pickbit-app" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["${ELASTICSEARCH_HOSTS:http://elasticsearch:9200}"]
    index => "pickbit-%{[environment]}-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
