spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
    loadbalancer:
      enabled: true

gateway:
  route:
    consul:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
