spring:
  config:
    import: optional:file:./secrets/application-deploy-secret.yml
    activate:
      on-profile: deploy

  data:
    redis:
      host: localhost
      port: 16379

  cloud:
    consul:
      enabled: true
      host: localhost
      port: 18500
      discovery:
        service-name: gateway-service
        health-check-path: /actuator/health
        health-check-interval: 10s

server:
  port: 18080

cors:
  allowed-origins:
    - "*"
