services:
  user-service:
    container_name: pickbit-deploy-user-service
    build:
      context: ../../..
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: user-service
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: deploy
      ENV: deploy
      LOG_PATH: /logs
      LOGSTASH_DESTINATION: logstash:5000
      JAVA_OPTS: -Xms512m -Xmx1024m
      CONSUL_HOST: consul-server
      CONSUL_PORT: 8500
      REDIS_HOST: redis
      REDIS_PORT: 6379
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_CLOUD_CONSUL_HOST: consul-server
      SPRING_CLOUD_CONSUL_PORT: 8500
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    volumes:
      - pickbit-deploy-logs:/logs
      - ../../../secrets:/app/secrets:ro
    networks:
      - pickbit-deploy

networks:
  pickbit-deploy:
    external: true

volumes:
  pickbit-deploy-logs:
    name: pickbit-backend_pickbit-deploy-logs
