spring:
  config:
    activate:
      on-profile: deploy

  cloud:
    consul:
      enabled: true
      host: ${CONSUL_HOST:consul-server}
      port: ${CONSUL_PORT:18500}

server:
  port: ${PAYMENT_SERVER_PORT:18086}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
