spring:
  application:
    name: payment-service

  cloud:
    consul:
      discovery:
        service-name: payment-service
        health-check-path: /actuator/health
        health-check-interval: 10s
        metadata:
          gateway-path: /api/payments/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
