spring:
  application:
    name: payment-service

  cloud:
    consul:
      discovery:
        service-name: payment-service
        health-check-path: /actuator/health
        health-check-interval: 10s
        metadata:
          gateway-path: /api/payments/**

management:
  endpoints:
    web:
      exposure:
        include: health,info

client:
  toss-payments:
    base-url: ${TOSS_BASE_URL}
    secret-key: ${TOSS_SECRET_KEY}
    success-url: ${TOSS_SUCCESS_URL}
    fail-url: ${TOSS_FAIL_URL}
    webhook-secret: ${TOSS_WEBHOOK_SECRET}
