spring:
  config:
    activate:
      on-profile: develop

server:
  port: 8083

openapi:
  docs-export:
    enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: false

ncp:
  storage:
    access-key: ncp_iam_BPAMKRhKcD2Ez1trhMv1
    secret-key: ncp_iam_BPKMKRQjQvHCpjkY9yhn9VlbVPtwmmGcJ6
    endpoint: https://kr.object.ncloudstorage.com
    region: kr-standard
    bucket-name: pickbit-server-develop-storage

