spring:
  config:
    import: optional:file:./secrets/application-develop-secret.yml
    activate:
      on-profile: develop

  cloud:
    consul:
      enabled: true
      host: localhost
      port: 18500

server:
  port: 18084

openapi:
  docs-export:
    enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: false

ncp:
  storage:
    access-key: ${NCP_STORAGE_ACCESS_KEY}
    secret-key: ${NCP_STORAGE_SECRET_KEY}
    endpoint: ${NCP_STORAGE_ENDPOINT}
    region: ${NCP_STORAGE_REGION}
    bucket-name: ${NCP_STORAGE_BUCKET_NAME}
