spring:
  config:
    import: optional:file:./secrets/application-deploy-secret.yml
    activate:
      on-profile: deploy

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${USER_MYSQL_USERNAME}
    password: ${USER_MYSQL_PASSWORD}
    url: ${USER_MYSQL_URL}

  kafka:
    bootstrap-servers: kafka:9092

  cloud:
    consul:
      enabled: true
      host: consul-server
      port: 8500

  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate

server:
  port: 18082

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
