spring:
  config:
    activate:
      on-profile: develop

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Rlawhdgns4!
    url: jdbc:mysql://localhost:3306/pickbit_user_server?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&allowPublicKeyRetrieval=true

  jpa:
    defer-datasource-initialization: false
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        use_sql_comments: false
        default_batch_fetch_size: 100
    database: mysql
    hibernate:
      ddl-auto: create

  kafka:
    bootstrap-servers: localhost:9092

  cloud:
    consul:
      enabled: true
      host: localhost
      port: 8500

server:
  port: 8082

openapi:
  docs-export:
    enabled: true
