spring:
  cloud:
    consul:
      enabled: true
      host: consul-server
      port: 8500

resilience4j:
  circuitbreaker:
    instances:
      productService:
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
  bulkhead:
    instances:
      productService:
        maxConcurrentCalls: 30
        maxWaitDuration: 100ms

server:
  port: 8085
