spring:
  config:
    activate:
      on-profile: develop

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Rlawhdgns4!
    url: jdbc:mysql://localhost:3306/pickbit_auction_server?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&allowPublicKeyRetrieval=true

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    defer-datasource-initialization: false
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        use_sql_comments: false
        default_batch_fetch_size: 100
    database: mysql
    hibernate:
      ddl-auto: create

server:
  port: 8085

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

client:
  product-service:
    base-url: http://localhost:8082

auction:
  scheduler:
    cron: "0 * * * * *"
