spring:
  config:
    import: optional:file:./secrets/application-deploy-secret.yml
    activate:
      on-profile: deploy

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${AUCTION_MYSQL_USERNAME}
    password: ${AUCTION_MYSQL_PASSWORD}
    url: ${AUCTION_MYSQL_URL}

  data:
    redis:
      host: redis
      port: 6379

  cloud:
    consul:
      enabled: true
      host: consul-server
      port: 8500

  jpa:
    defer-datasource-initialization: false
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        use_sql_comments: false
        default_batch_fetch_size: 100
    database: mysql
    hibernate:
      ddl-auto: validate

server:
  port: 18085


client:
  product-service:
    base-url: http://product-service:18083
  user-service:
    base-url: http://user-service:18082

auction:
  scheduler:
    cron: "0 * * * * *"
  cache:
    auction-ttl-seconds: 10

resilience4j:
  circuitbreaker:
    instances:
      productService:
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
      userService:
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
  bulkhead:
    instances:
      productService:
        maxConcurrentCalls: 30
        maxWaitDuration: 100ms
      userService:
        maxConcurrentCalls: 30
        maxWaitDuration: 100ms

openapi:
  docs-export:
    enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: false
