spring:
  config:
    import: optional:file:./secrets/application-deploy-secret.yml
    activate:
      on-profile: deploy

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${PRODUCT_MYSQL_USERNAME}
    password: ${PRODUCT_MYSQL_PASSWORD}
    url: ${PRODUCT_MYSQL_URL}

  jpa:
    defer-datasource-initialization: false
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        use_sql_comments: false
        default_batch_fetch_size: 100
    database: mysql
    hibernate:
      ddl-auto: validate

  kafka:
    bootstrap-servers: kafka:9092

  data:
    redis:
      host: redis
      port: 6379
      timeout: 2s
      lettuce:
        pool:
          enabled: true
          max-active: 32
          max-idle: 16
          min-idle: 4
          max-wait: 1s

  cloud:
    consul:
      enabled: true
      host: consul-server
      port: 8500


server:
  port: 18083

client:
  auction-service:
    base-url: http://auction-service:18085

ncp:
  storage:
    access-key: ${NCP_STORAGE_ACCESS_KEY}
    secret-key: ${NCP_STORAGE_SECRET_KEY}
    endpoint: ${NCP_STORAGE_ENDPOINT}
    region: ${NCP_STORAGE_REGION}
    bucket-name: ${NCP_STORAGE_BUCKET_NAME}

openapi:
  docs-export:
    enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: false
