spring:
  config:
    import: optional:file:./secrets/application-deploy-secret.yml
    activate:
      on-profile: deploy

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${PRODUCT_MYSQL_USERNAME}
    password: ${PRODUCT_MYSQL_PASSWORD}
    url: ${PRODUCT_MYSQL_URL}

  cloud:
    consul:
      enabled: true
      host: consul-server
      port: 8500

  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 100

server:
  port: 18083

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
