spring:
  application:
    name: product-service

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        model: ${OPENAI_CHAT_MODEL}
        temperature: ${OPENAI_CHAT_TEMPERATURE}

  cloud:
    consul:
      discovery:
        service-name: product-service
        health-check-path: /actuator/health
        health-check-interval: 10s
        metadata:
          gateway-path: /api/products/**,/api/categories/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
